// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZqwodvMFh4WeEl58wh4h7csgr9nJadCY',
    appId: '1:747199122480:web:d5ff6079cb6fb2771f31f5',
    messagingSenderId: '747199122480',
    projectId: 'nomad-8a59b',
    authDomain: 'nomad-8a59b.firebaseapp.com',
    storageBucket: 'nomad-8a59b.firebasestorage.app',
    measurementId: 'G-H2X1D3VN64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQvLIuLn2AhGmLzKU_rGIzKgt2ffCGfHg',
    appId: '1:747199122480:android:bb8d2364336b40881f31f5',
    messagingSenderId: '747199122480',
    projectId: 'nomad-8a59b',
    storageBucket: 'nomad-8a59b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmZlNE2xSVJwxcoAfJXgavE4Xcxr1efOs',
    appId: '1:747199122480:ios:5e61bb3f18d0ea8b1f31f5',
    messagingSenderId: '747199122480',
    projectId: 'nomad-8a59b',
    storageBucket: 'nomad-8a59b.firebasestorage.app',
    iosBundleId: 'com.example.nomad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmZlNE2xSVJwxcoAfJXgavE4Xcxr1efOs',
    appId: '1:747199122480:ios:5e61bb3f18d0ea8b1f31f5',
    messagingSenderId: '747199122480',
    projectId: 'nomad-8a59b',
    storageBucket: 'nomad-8a59b.firebasestorage.app',
    iosBundleId: 'com.example.nomad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZqwodvMFh4WeEl58wh4h7csgr9nJadCY',
    appId: '1:747199122480:web:5f5b1266c182e9e71f31f5',
    messagingSenderId: '747199122480',
    projectId: 'nomad-8a59b',
    authDomain: 'nomad-8a59b.firebaseapp.com',
    storageBucket: 'nomad-8a59b.firebasestorage.app',
    measurementId: 'G-1R882TFJ5E',
  );
}
